export interface AlchemistQuestion {
  id: string;
  loreLabId: string;
  domain: string;
  topic: string;
  question: string;
  options: string[];
  correctOption: string;
  analysis: string;
  hint: string;
  context: string;
}

export const ALCHEMIST_QUESTIONS: AlchemistQuestion[] = [
  {
    "id": "FAC_01",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "THERMO",
    "topic": "MATH",
    "question": "What is the relationship between Kp and Kc for: N2(g) + 3H2(g) <=> 2NH3(g)?",
    "options": [
      "Kp = Kc(RT)",
      "Kp = Kc(RT)^-2",
      "Kp = Kc(RT)^2"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ (RT) assumes Delta n = 1. || ✅ Delta n = (moles gas prod) - (moles gas react) = 2 - 4 = -2. Thus Kp = Kc(RT)^-2.",
    "hint": "Count gas moles.",
    "context": "Van't Hoff Equation"
  },
  {
    "id": "FAC_02",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETIC",
    "topic": "MATH",
    "question": "If activation energy (Ea) is 50 kJ/mol, by what factor does rate increase from 300K to 310K?",
    "options": [
      "~1.5x",
      "~2.0x",
      "~3.0x"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 1.5 is too low for 50kJ. || ✅ Using ln(k2/k1) = (Ea/R)(1/T1 - 1/T2), the ratio is approx 1.95, roughly 2.",
    "hint": "Arrhenius factor.",
    "context": "Arrhenius Equation"
  },
  {
    "id": "FAC_03",
    "loreLabId": "quantum-forge",
    "domain": "QUANTUM",
    "topic": "MATH",
    "question": "Energy of a particle in a 1D box (length L) in the second excited state (n=3)?",
    "options": [
      "h^2 / 8mL^2",
      "9h^2 / 8mL^2",
      "4h^2 / 8mL^2"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ n=1 is ground. n=2 is 1st excited. || ✅ Second excited state means n=3. E = (n^2 * h^2) / (8mL^2).",
    "hint": "n=3 square it.",
    "context": "Schrodinger Equation"
  },
  {
    "id": "FAC_04",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "ANALYT",
    "topic": "MATH",
    "question": "In HPLC, if tR = 5 min and w = 0.5 min, calculate theoretical plates (N).",
    "options": [
      "1600",
      "1600",
      "100"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 100 is too low. || ✅ N = 16 * (tR / w)^2 = 16 * (5 / 0.5)^2 = 16 * 100 = 1600.",
    "hint": "Plate count square.",
    "context": "Chromatography Efficiency"
  },
  {
    "id": "FAC_05",
    "loreLabId": "inorganic-lattice-vault",
    "domain": "INORG",
    "topic": "MATH",
    "question": "Calculate CFSE for a d6 high-spin octahedral complex.",
    "options": [
      "-2.4 Delta_o",
      "-0.4 Delta_o",
      "0 Delta_o"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ -2.4 is low spin. || ✅ High spin d6: (t2g)4 (eg)2. CFSE = [4*(-0.4) + 2*(0.6)] = -0.4 Delta_o.",
    "hint": "Split the electrons.",
    "context": "Crystal Field Theory"
  },
  {
    "id": "FAC_06",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "MATH",
    "question": "How many 1H NMR signals are in 1,2-dichloroethane?",
    "options": [
      "2",
      "1",
      "4"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 2 implies asymmetry. || ✅ All 4 hydrogens are chemically and magnetically equivalent due to symmetry. Total = 1 signal.",
    "hint": "Symmetry equivalence.",
    "context": "NMR Spectroscopy"
  },
  {
    "id": "FAC_07",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "THERMO",
    "topic": "MATH",
    "question": "Ionic strength (I) of 0.1 M Na2SO4 solution?",
    "options": [
      "0.1 M",
      "0.3 M",
      "0.2 M"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 0.1 M is for 1:1 salt. || ✅ I = 0.5 * sum(ci * zi^2) = 0.5 * (0.2*1^2 + 0.1*2^2) = 0.3 M.",
    "hint": "Sum of charges sq.",
    "context": "Debye-Huckel Theory"
  },
  {
    "id": "FAC_08",
    "loreLabId": "quantum-forge",
    "domain": "QUANTUM",
    "topic": "MATH",
    "question": "Uncertainty in velocity (Delta v) if Delta x = 1.0 Angstrom for an electron?",
    "options": [
      "5.8e5 m/s",
      "5.8e5 m/s",
      "1.0e6 m/s"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 1.0e6 is a guess. || ✅ Delta v = h / (4pi * m * Delta x). Calculation yields ~5.8e5 m/s.",
    "hint": "Heisenberg math.",
    "context": "Uncertainty Principle"
  },
  {
    "id": "FAC_09",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "ANALYT",
    "topic": "MATH",
    "question": "Peak separation (Delta Ep) for a reversible 1-electron CV transfer?",
    "options": [
      "29 mV",
      "59 mV",
      "0 mV"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 29 mV is for n=2. || ✅ For a reversible Nernstian couple, Delta Ep = 59/n mV at 25C.",
    "hint": "The 59/n rule.",
    "context": "Cyclic Voltammetry"
  },
  {
    "id": "FAC_10",
    "loreLabId": "inorganic-lattice-vault",
    "domain": "INORG",
    "topic": "MATH",
    "question": "Spin-only magnetic moment for Co2+ (d7) in tetrahedral field?",
    "options": [
      "1.73 BM",
      "3.87 BM",
      "4.90 BM"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 4.90 is d6. || ✅ Co2+ (d7) tetrahedral is high spin (e4 t2 3). 3 unpaired e-. sqrt(3*5) = 3.87 BM.",
    "hint": "Tetrahedral flip.",
    "context": "Magnetochemistry"
  },
  {
    "id": "FAC_11",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "MATH",
    "question": "Degree of unsaturation (DoU) for C6H10O?",
    "options": [
      "1",
      "2",
      "3"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 1 is for C6H12. || ✅ DoU = C + 1 - H/2 = 6 + 1 - 5 = 2. (Could be 2 rings, 2 pi bonds).",
    "hint": "Missing Hydrogens.",
    "context": "Formula Analysis"
  },
  {
    "id": "FAC_12",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETIC",
    "topic": "MATH",
    "question": "For 2nd order (A->P), t=20min for 1.0M to 0.5M. Time to drop 0.5M to 0.25M?",
    "options": [
      "20 min",
      "40 min",
      "60 min"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 20 min is 1st order. || ✅ In 2nd order, half-life doubles as concentration halves. 20 * 2 = 40 min.",
    "hint": "Half-life doubles.",
    "context": "Integrated Rate Laws"
  },
  {
    "id": "FAC_13",
    "loreLabId": "statmech-probability-drive",
    "domain": "STATMEC",
    "topic": "MATH",
    "question": "Rotational partition function (qr) for heteronuclear diatomic at high T?",
    "options": [
      "kT / hB",
      "kT / hcB",
      "kT / 2hcB"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ 2hcB is homonuclear. || ✅ For sigma=1 (heteronuclear), qr = kT / hcB.",
    "hint": "Sigma is 1.",
    "context": "Partition Functions"
  },
  {
    "id": "FAC_14",
    "loreLabId": "inorganic-lattice-vault",
    "domain": "INORG",
    "topic": "LOGIC",
    "question": "Why is 'Trans Influence' strong for high pi-acidity ligands?",
    "options": [
      "Donates electrons",
      "Weakens trans bond via d-orbital competition",
      "It is steric"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Sterics are secondary. || ✅ They withdraw density from the same metal d-orbitals used by the trans ligand, weakening its bond.",
    "hint": "Orbital competition.",
    "context": "Trans Effect"
  },
  {
    "id": "FAC_15",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "LOGIC",
    "question": "In 'Robinson Annulation', what are the two sequential reactions?",
    "options": [
      "Aldol + Wittig",
      "Michael + Aldol",
      "Michael + Claisen"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Wittig makes alkenes. || ✅ It begins with a Michael addition followed by an intramolecular Aldol condensation.",
    "hint": "Michael-Aldol combo.",
    "context": "Ring Formation"
  },
  {
    "id": "FAC_16",
    "loreLabId": "quantum-forge",
    "domain": "QUANTUM",
    "topic": "LOGIC",
    "question": "Physical origin of 'Exchange Energy' in multi-electron systems?",
    "options": [
      "Coulomb only",
      "Pauli Principle + Coulomb repulsion",
      "Gravity"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Gravity is weak. || ✅ Antisymmetry keeps same-spin electrons apart (Fermi Hole), reducing their Coulomb repulsion.",
    "hint": "Fermi Hole.",
    "context": "Hartree-Fock"
  },
  {
    "id": "FAC_17",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "ANALYT",
    "topic": "LOGIC",
    "question": "Why use 'Internal Standard' in quantitative GC?",
    "options": [
      "Clean syringe",
      "Account for injection volume variation",
      "Lower BP"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Syringes are cleaned manually. || ✅ It compensates for human error in injection volume or instrument drift.",
    "hint": "Ratio correction.",
    "context": "Quantitative GC"
  },
  {
    "id": "FAC_18",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "THERMO",
    "topic": "LOGIC",
    "question": "What implies a 'Negative' Volume of Activation (Delta V++)?",
    "options": [
      "Slower at high P",
      "Faster at high P",
      "No change"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Positive Delta V++ means high P slows rate. || ✅ Negative means the Transition State is more compact, so Pressure accelerates it.",
    "hint": "Compression helps.",
    "context": "Transition State Theory"
  },
  {
    "id": "FAC_19",
    "loreLabId": "inorganic-lattice-vault",
    "domain": "INORG",
    "topic": "LOGIC",
    "question": "Why 'Inverse' Spinel for Fe3O4?",
    "options": [
      "Lattice Energy",
      "CFSE of Fe(II) vs Fe(III)",
      "Size mismatch"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Lattice is similar. || ✅ Fe(III) is d5 (0 CFSE). Fe(II) is d6 and gains stability in the octahedral B-site.",
    "hint": "Site preference.",
    "context": "Solid State Chem"
  },
  {
    "id": "FAC_20",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "LOGIC",
    "question": "Endo' selectivity in Diels-Alder is due to?",
    "options": [
      "Sterics",
      "Secondary Orbital Interactions",
      "Entropy"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Endo is often more crowded. || ✅ Overlap between the pi-system of the substituent and the diene stabilizes the endo TS.",
    "hint": "Pi-overlap.",
    "context": "Frontier Orbitals"
  },
  {
    "id": "FAC_21",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETIC",
    "topic": "LOGIC",
    "question": "Steady-State Approximation' implies?",
    "options": [
      "Concentration = 0",
      "Rate of formation = Rate of loss",
      "Time = infinity"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Conc is small, not zero. || ✅ It assumes d[I]/dt = 0 for highly reactive intermediates.",
    "hint": "Flux balance.",
    "context": "Reaction Mechanisms"
  },
  {
    "id": "FAC_22",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "ANALYT",
    "topic": "LOGIC",
    "question": "Why use 'Deuterated' solvent in NMR?",
    "options": [
      "Solubility",
      "Avoid solvent signal interference",
      "Cooling"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Solubility is same. || ✅ Deuterium resonates at a different frequency, making the solvent 'invisible' in 1H NMR.",
    "hint": "Invisible solvent.",
    "context": "NMR Technique"
  },
  {
    "id": "FAC_23",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "LAB",
    "topic": "PRAC",
    "question": "Primary risk of heating a 'Closed System'?",
    "options": [
      "Solvent loss",
      "Explosion",
      "Slow reaction"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Closed prevents loss. || ✅ PV=nRT. increasing T in fixed V causes massive P increase -> Explosion.",
    "hint": "Pressure bomb.",
    "context": "Lab Safety"
  },
  {
    "id": "FAC_24",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "LAB",
    "topic": "PRAC",
    "question": "Why 'Acid to Water' during dilution?",
    "options": [
      "Better mixing",
      "Heat dissipation (Safety)",
      "Reaction speed"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Water to acid causes boiling/splashing. || ✅ High heat capacity of water absorbs the exothermic energy safely.",
    "hint": "AA (Add Acid).",
    "context": "Lab Safety"
  },
  {
    "id": "FAC_25",
    "loreLabId": "analytical-spectre-scanner",
    "domain": "LAB",
    "topic": "PRAC",
    "question": "Function of 'Boric Acid' in Kjeldahl method?",
    "options": [
      "Digest protein",
      "Trap distilled ammonia",
      "Catalyst"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Digestion uses H2SO4. || ✅ Ammonia distilled is captured in boric acid to form ammonium borate for titration.",
    "hint": "Ammonia trap.",
    "context": "Analytical Lab"
  },
  {
    "id": "FAC_26",
    "loreLabId": "quantum-forge",
    "domain": "QUANTUM",
    "topic": "LOGIC",
    "question": "Born-Oppenheimer' approx fails when?",
    "options": [
      "Mass is high",
      "Energy surfaces touch (Conical Intersection)",
      "Relativistic"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Mass usually justifies it. || ✅ When energy gap vanishes, nuclear and electronic timescales mix.",
    "hint": "Surfaces touch.",
    "context": "Non-adiabatic dynamics"
  },
  {
    "id": "FAC_27",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "THERMO",
    "topic": "LOGIC",
    "question": "Critical Opalescence' is caused by?",
    "options": [
      "Solidification",
      "Density fluctuations scattering light",
      "Absorption"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Fluid remains fluid. || ✅ Near critical point, density fluctuations match light wavelength -> scattering.",
    "hint": "Fluctuation scattering.",
    "context": "Phase Transitions"
  },
  {
    "id": "FAC_28",
    "loreLabId": "inorganic-lattice-vault",
    "domain": "INORG",
    "topic": "LOGIC",
    "question": "Jahn-Teller' distortion in d9 octahedral?",
    "options": [
      "Increase symmetry",
      "Remove degeneracy / Lower energy",
      "Sterics"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ It lowers symmetry (Oh to D4h). || ✅ Distorting splits the degenerate levels, putting the odd electron in a lower energy orbital.",
    "hint": "Split to save.",
    "context": "Electronic Structure"
  },
  {
    "id": "FAC_29",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "LOGIC",
    "question": "Favorskii' rearrangement mechanism?",
    "options": [
      "Radical",
      "Concerted cyclopropanone formation",
      "Carbocation"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Radical is different. || ✅ Base removes alpha-H, forming a cyclopropanone intermediate via internal SN2.",
    "hint": "3-membered ring.",
    "context": "Mechanisms"
  },
  {
    "id": "FAC_30",
    "loreLabId": "statmech-probability-drive",
    "domain": "STATMEC",
    "topic": "LOGIC",
    "question": "Ergodicity' means?",
    "options": [
      "High entropy",
      "Time average = Ensemble average",
      "Chaos"
    ],
    "correctOption": "RIGHT",
    "analysis": "❌ Chaos is different. || ✅ The system visits all possible states over time, so one trace represents the whole group.",
    "hint": "Sampling everything.",
    "context": "Statistical Mechanics"
  },
  {
    "id": "MSTR_001",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Thermodynamic Work Definitions",
    "question": "In a reversible isothermal expansion of an ideal gas",
    "options": [],
    "correctOption": "what is the formula for the work done by the system?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_002",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Internal Energy vs Enthalpy",
    "question": "For an ideal gas undergoing an isothermal expansion",
    "options": [],
    "correctOption": "what is the value of the change in internal energy (Δ<i>U</i>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_003",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Elementary Reaction Concepts",
    "question": "What does the molecularity of an elementary reaction represent?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Molecularity is the number of reactant particles that must collide simultaneously to effect the chemical change in a single step.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_004",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Nucleophilicity vs Basicity",
    "question": "In a polar aprotic solvent like DMSO",
    "options": [],
    "correctOption": "which halide ion is the strongest nucleophile?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_005",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Standard Reduction Potentials",
    "question": "What does a positive standard reduction potential (<i>E</i>°) for a half-cell signify?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> A positive <i>E</i>° indicates the species is a stronger oxidizing agent than <i>H</i><sup>+</sup>",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_006",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Spontaneity Criteria",
    "question": "A galvanic cell operates spontaneously when the Gibbs free energy change (Δ<i>G</i>) and the cell potential (<i>E</i><sub>cell</sub>) satisfy which conditions?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Spontaneity requires Δ<i>G</i> to be negative. According to Δ<i>G</i> = −<i>nFE</i>",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_007",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Hybridization in Alkanes",
    "question": "What is the hybridization and geometry of the carbon atom in methane?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Carbon in methane has four sigma bonds and no lone pairs",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_008",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Rate Constant Units",
    "question": "For a reaction that follows second-order kinetics",
    "options": [],
    "correctOption": "what are the units of the rate constant (<i>k</i>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_009",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Ideal Gas Law Limits",
    "question": "Which variable represents the volume of individual molecules in the van der Waals equation?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The <i>b</i> parameter represents the \"excluded volume\" per mole",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_010",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Partial Molar Volumes",
    "question": "Is the partial molar volume of a component in a mixture always equal to its molar volume in the pure state?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Partial molar volume (<i>V</i><sub>i</sub>) accounts for the change in total volume per mole of component <i>i</i> added. Interactions between different species cause <i>V</i><sub>i</sub> to deviate from the pure molar volume.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_011",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Enthalpy of Phase Changes",
    "question": "Why is the enthalpy of vaporization (Δ<i>H</i><sub>vap</sub>) always greater than the enthalpy of fusion (Δ<i>H</i><sub>fus</sub>) for a substance?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Fusion only requires partial disruption of the lattice",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_012",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Atropisomerism",
    "question": "Which structural feature is necessary for a biphenyl derivative to exhibit atropisomerism and be resolved into enantiomers?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Atropisomers are stereoisomers resulting from restricted rotation about a single bond where the rotational barrier is high enough to allow isolation of the conformers.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_013",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Temperature Dependence of Rates",
    "question": "According to the Arrhenius equation",
    "options": [],
    "correctOption": "why does the reaction rate increase with temperature?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_014",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Salt Bridge Function",
    "question": "What is the primary role of the salt bridge in a standard voltaic cell?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> As oxidation and reduction occur",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_015",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Nernst Equation Application",
    "question": "How does the cell potential (<i>E</i><sub>cell</sub>) change as the reaction quotient (<i>Q</i>) increases?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> As products accumulate (higher <i>Q</i>)",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_016",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Zero-Order Kinetics",
    "question": "In a zero-order reaction",
    "options": [],
    "correctOption": "how does the half-life (<i>t</i><sub>1/2</sub>) change as the initial concentration of the reactant ([A]<sub>0</sub>) increases?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_017",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Inductive Effects in Acids",
    "question": "Why is trifluoroacetic acid a much stronger acid than acetic acid?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The strong inductive effect (-I) of the three fluorine atoms withdraws electron density",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_018",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Entropy of Phase Changes",
    "question": "When a liquid is supercooled below its normal freezing point and then freezes spontaneously",
    "options": [],
    "correctOption": "what is the sign of the total entropy change of the universe (Δ<i>S</i><sub>total</sub>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_019",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Colligative Property Logic",
    "question": "Why does the addition of a non-volatile solute lower the vapor pressure of a solvent?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Raoult's Law states <i>P</i> = <i>xP</i>°; adding solute lowers the mole fraction (<i>x</i>) of the solvent",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_020",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "S<sub>N</sub>1 vs S<sub>N</sub>2 Solvolysis",
    "question": "How does increasing the polarity of a protic solvent (e.g.",
    "options": [],
    "correctOption": "water/ethanol mixtures) affect the rate of an S<sub>N</sub>1 reaction of an alkyl halide?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_021",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Entropy and Spontaneity",
    "question": "For a process to be spontaneous at constant <i>T</i> and <i>P</i>",
    "options": [],
    "correctOption": "what must be true?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_022",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Standard Hydrogen Electrode",
    "question": "In the Standard Hydrogen Electrode (SHE)",
    "options": [],
    "correctOption": "why is the surface of the platinum electrode coated with platinum black?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_023",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Catalysis Mechanisms",
    "question": "How does a catalyst increase the rate of a chemical reaction?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> A catalyst offers an alternative mechanistic pathway with a lower activation energy",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_024",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Collision Frequency",
    "question": "According to collision theory",
    "options": [],
    "correctOption": "how does the collision frequency (<i>Z</i>) between two gas-phase molecules depend on the absolute temperature (<i>T</i>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_025",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Salt Bridge Function",
    "question": "What is the primary role of a salt bridge in a galvanic cell?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The salt bridge allows for the migration of ions to balance the charge generated by electron flow",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_026",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Fugacity and Ideality",
    "question": "Under what conditions is the fugacity (<i>f</i>) of a real gas numerically equal to its partial pressure (<i>P</i><sub>i</sub>)?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> As <i>P</i> → 0",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_027",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "S<sub>N</sub>2 Reaction Stereochemistry",
    "question": "What is the stereochemical outcome of an S<sub>N</sub>2 reaction at a chiral center?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The nucleophile attacks the back lobe of the C-L sigma* orbital",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_028",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Nitration of Phenol",
    "question": "In the electrophilic aromatic nitration of phenol",
    "options": [],
    "correctOption": "why is the reaction significantly faster than the nitration of benzene?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_029",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Partial Molar Quantities",
    "question": "What does the chemical potential (μ) of a component in a mixture represent?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Chemical potential is defined as (∂<i>G</i>/∂<i>n<sub>i</sub></i>) at constant <i>T",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_030",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Concentration and Cell Potential",
    "question": "If the concentration of the reactants in a spontaneous galvanic cell is increased while the product concentration is held constant",
    "options": [],
    "correctOption": "how does the cell potential (<i>E</i><sub>cell</sub>) change?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_031",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Reaction Order Units",
    "question": "What are the units of the rate constant (<i>k</i>) for a second-order reaction?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> For a second-order reaction",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_032",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Parallel Reaction Selectivity",
    "question": "In a system where reactant A can form either Product B or Product C via parallel first-order steps (<i>k</i><sub>B</sub> and <i>k</i><sub>C</sub>)",
    "options": [],
    "correctOption": "what determines the ratio of [B]/[C] at any time <i>t</i>?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_033",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Alkyne Geometry",
    "question": "What is the carbon-carbon bond angle in ethyne (acetylene)?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Each carbon in ethyne is <i>sp</i>-hybridized with two electron domains",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_034",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Chemical Potential",
    "question": "Which partial derivative defines the chemical potential (μ<sub>i</sub>) of a component in terms of the Gibbs free energy (<i>G</i>)?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The chemical potential is the partial molar Gibbs free energy",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_035",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Standard State Definitions",
    "question": "Which condition defines the standard state for a gas?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The standard state of a gas is the pure substance at a pressure of exactly 1 bar (100 kPa). Temperature is usually specified but not part of the state definition.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_036",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "The Lever Rule",
    "question": "In a binary phase diagram",
    "options": [],
    "correctOption": "what does the Lever Rule allow a researcher to calculate?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_037",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Resonance Stability",
    "question": "Why is the acetate ion more stable than the ethoxide ion?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> In acetate",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_038",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Keto-Enol Equilibrium",
    "question": "Why does 2",
    "options": [],
    "correctOption": "4-pentanedione (acetylacetone) exist with a significant percentage of the enol tautomer in non-polar solvents",
    "analysis": "unlike simple ketones?",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_039",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Half-life of First-Order Reactions",
    "question": "How does the half-life of a first-order reaction change as the initial concentration is doubled?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> For first-order reactions",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_040",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Mean Ionic Activity",
    "question": "For a 1:2 electrolyte like MgCl<sub>2</sub>",
    "options": [],
    "correctOption": "how is the mean ionic activity (<i>a</i><sub>±</sub>) related to the activities of the individual ions (<i>a</i><sub>+</sub> and <i>a</i><sub>−</sub>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_041",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Hess's Law Foundations",
    "question": "Why is the enthalpy change for a reaction independent of the number of steps?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Since enthalpy (<i>H</i>) depends only on the current state",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_042",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Lindemann Mechanism",
    "question": "According to the Lindemann mechanism for unimolecular reactions",
    "options": [],
    "correctOption": "under what condition does the reaction follow first-order kinetics?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_043",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Reaction Coordinate Diagrams",
    "question": "On a potential energy diagram",
    "options": [],
    "correctOption": "what does the peak of the curve represent?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_044",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Third Law of Thermodynamics",
    "question": "What is the physical implication of the Third Law of Thermodynamics regarding the entropy of a perfectly crystalline substance?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The Third Law states that the entropy of a perfect crystal is zero at 0 K",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_045",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Electrophilic Addition Regioselectivity",
    "question": "According to Markovnikov's rule",
    "options": [],
    "correctOption": "where does the hydrogen atom add in HX addition to an alkene?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_046",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Electrocyclic Ring Closure",
    "question": "According to the Woodward-Hoffmann rules",
    "options": [],
    "correctOption": "what is the stereochemical outcome for the thermal ring closure of (2<i>E</i>",
    "analysis": "4<i>Z</i>",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_047",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Raoult's Law Deviations",
    "question": "What causes a negative deviation from Raoult's Law in a binary liquid mixture?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> When A-B attractions are stronger than A-A or B-B",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_048",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Kohlrausch's Law",
    "question": "What does the Law of Independent Migration of Ions (Kohlrausch's Law) describe for strong electrolytes at infinite dilution?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> At infinite dilution",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_049",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Electrolysis Stoichiometry",
    "question": "According to Faraday's laws",
    "options": [],
    "correctOption": "what determines the mass of a substance produced at an electrode?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_050",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Relaxation Kinetics",
    "question": "In a T-jump experiment for a fast reaction",
    "options": [],
    "correctOption": "what physical quantity is used to determine the rate constants?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_051",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Heat Capacity at Phase Transitions",
    "question": "What is the effective heat capacity (<i>C</i>) of a pure substance during a first-order phase transition?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Since heat is added (d<i>q</i> > 0) while d<i>T</i> is zero",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_052",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Kinetic vs Thermodynamic Enolates",
    "question": "(SOFT TRAP) When treating an unsymmetrical ketone like 2-methylcyclohexanone with a strong",
    "options": [],
    "correctOption": "bulky base (LDA) at −78 °C",
    "analysis": "which enolate is predominantly formed?",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_053",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Steady-State Approximation",
    "question": "Under what condition is the Steady-State Approximation (SSA) valid for an intermediate [I]?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The SSA is valid when the intermediate is highly reactive and its concentration remains small and nearly constant after an initial induction period.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_054",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Compressibility Factor",
    "question": "(SOFT TRAP) For a real gas at its Boyle temperature (<i>T</i><sub>B</sub>)",
    "options": [],
    "correctOption": "how does the compressibility factor (<i>Z</i> = <i>PV/nRT</i>) behave as the pressure (<i>P</i>) approaches zero?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_055",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Kinetic vs Thermodynamic Control",
    "question": "Which product dominates in a reaction under kinetic control?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Kinetic control favors the product that forms the fastest",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_056",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Potentiostatic vs Galvanostatic",
    "question": "(SOFT TRAP) In a three-electrode electrochemical setup",
    "options": [],
    "correctOption": "which electrode's potential is strictly controlled and measured against the Reference Electrode?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_057",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Liquid Junction Potentials",
    "question": "What is the source of the potential difference at the interface of two different electrolyte solutions?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Unequal diffusion rates of cations and anions create a charge separation and a resulting electric potential at the junction.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_058",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Symmetry in TST",
    "question": "(SOFT TRAP) In Transition State Theory",
    "options": [],
    "correctOption": "how does the inclusion of a symmetry number (σ) affect the calculated rate of a reaction like H + H<sub>2</sub> → H<sub>2</sub> + H?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_059",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Partial Pressures and Dalton's Law",
    "question": "In a mixture of real gases",
    "options": [],
    "correctOption": "is the total pressure exactly equal to the sum of the pressures of the pure components at the same <i>T",
    "analysis": "V</i>?",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_060",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Sugar Epimerization",
    "question": "(SOFT TRAP) In the base-catalyzed interconversion of D-glucose",
    "options": [],
    "correctOption": "D-mannose",
    "analysis": "and D-fructose (Lobry de Bruyn–van Ekenstein transformation)",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_061",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Carbocation Rearrangements",
    "question": "Why does a secondary carbocation undergo a 1",
    "options": [],
    "correctOption": "2-hydride shift to form a tertiary carbocation?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_062",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Colligative Non-ideality",
    "question": "(SOFT TRAP) For a real solution",
    "options": [],
    "correctOption": "if the activity coefficient (γ) of the solvent is less than 1.0",
    "analysis": "how will the observed boiling point elevation compare to the ideal prediction?",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_063",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Chain Reaction Mechanisms",
    "question": "What defines the initiation step in a radical chain reaction?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Initiation is the step that creates the first radicals in the system",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_064",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Charge Transfer Resistance",
    "question": "(SOFT TRAP) According to the Butler-Volmer equation",
    "options": [],
    "correctOption": "what happens to the charge transfer resistance (<i>R</i><sub>ct</sub>) as the exchange current density (<i>j</i><sub>0</sub>) of an electrode increases?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_065",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Phase Rule and Degrees of Freedom",
    "question": "According to Gibbs Phase Rule (<i>F = C − P + 2</i>)",
    "options": [],
    "correctOption": "how many degrees of freedom exist at the triple point of water?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_066",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Langmuir-Hinshelwood",
    "question": "(SOFT TRAP) In the Langmuir-Hinshelwood mechanism for a surface reaction (A + B → P)",
    "options": [],
    "correctOption": "what is the rate-determining step?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_067",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Overpotential in Electrolysis",
    "question": "Why is the voltage required for water electrolysis higher than the calculated 1.23 V?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> Overpotential accounts for the activation energy of the electron transfer and the formation of gas bubbles",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_068",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Radical Stability",
    "question": "(SOFT TRAP) Which effect explains why a radical with both an electron-withdrawing group and an electron-donating group on the same carbon is unusually stable?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The captodative effect describes the enhanced stabilization of a radical by the combined action of an electron-withdrawing (capto) and an electron-donating (dative) substituent.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_069",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Nucleophilic Substitution in Aryl Halides",
    "question": "Why are aryl halides typically unreactive toward S<sub>N</sub>2 reactions?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> The nucleophile would have to attack through the center of the ring (physically impossible) and overcome electron-electron repulsion with the pi-system.",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_070",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Virial Osmotic Pressure",
    "question": "(SOFT TRAP) For a polymer solution",
    "options": [],
    "correctOption": "why does the plot of (Π/<i>c</i>) versus concentration (<i>c</i>) have a non-zero slope?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_071",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Standard vs Actual Free Energy",
    "question": "Can a reaction with a positive Δ<i>G</i>° proceed spontaneously toward products?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) Δ<i>G</i>° only defines the equilibrium constant <i>K</i>. If <i>Q</i> << <i>K</i>",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_072",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Cyclic Voltammetry Peaks",
    "question": "(SOFT TRAP) For a reversible",
    "options": [],
    "correctOption": "one-electron redox process",
    "analysis": "what is the theoretical peak-to-peak separation (Δ<i>E</i><sub>p</sub>) at 298 K?",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_073",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "The Equilibrium-Rate Relationship",
    "question": "Does a large equilibrium constant (<i>K</i> >> 1) imply a fast reaction rate?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) <i>K</i> relates to the relative energies of reactants and products",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_074",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Diffusion-Controlled Limit",
    "question": "(SOFT TRAP) If a solution-phase reaction is diffusion-controlled",
    "options": [],
    "correctOption": "how does the rate constant (<i>k</i><sub>diff</sub>) change when the viscosity of the solvent is doubled?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_075",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "The Curtin-Hammett Principle",
    "question": "In a system with two interconverting conformers A ⇌ B",
    "options": [],
    "correctOption": "which factor determines the product ratio P<sub>A</sub> : P<sub>B</sub>?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_076",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Cram's Rule",
    "question": "(SOFT TRAP) In the nucleophilic addition to a chiral carbonyl compound",
    "options": [],
    "correctOption": "which model predicts the major diastereomer based on the Large",
    "analysis": "Medium",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_077",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "The Ideal Solution Trap",
    "question": "In an ideal solution",
    "options": [],
    "correctOption": "is the enthalpy of mixing (Δ<i>H</i><sub>mix</sub>) zero because there are no intermolecular forces?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_078",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Gibbs Paradox",
    "question": "(EXPERT TRAP) Two separate containers of the same ideal gas at the same <i>T</i> and <i>P</i> are allowed to mix. Is there an entropy of mixing (Δ<i>S</i><sub>mix</sub>) for this process?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) Because the particles are identical and indistinguishable",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_079",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "The EMF and Stoichiometry",
    "question": "If you double the stoichiometric coefficients of a redox reaction",
    "options": [],
    "correctOption": "what happens to the cell potential (<i>E</i>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_080",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Aromaticity of [10]-Annulene",
    "question": "(EXPERT TRAP) Is [10]-annulene (cyclodecapentaene) considered a stable aromatic compound like benzene?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) While it has 10 pi-electrons (4n+2)",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_081",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Aromaticity and Electron Count",
    "question": "Is the cyclooctatetraene (COT) molecule aromatic due to its cyclic conjugated pi-system?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) COT has 8 pi-electrons (4n). To avoid anti-aromatic destabilization",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_082",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Potential of Zero Charge",
    "question": "(EXPERT TRAP) At the Potential of Zero Charge (PZC) for a metal electrode",
    "options": [],
    "correctOption": "is the total electrical potential difference across the interface zero?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_083",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Colligative Properties and Molarity",
    "question": "Why is molality (<i>m</i>) used instead of molarity (<i>M</i>) in boiling point elevation calculations?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) Molarity depends on volume",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_084",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Pre-equilibrium vs SSA",
    "question": "(EXPERT TRAP) For a reaction A + B ⇌ I → P",
    "options": [],
    "correctOption": "under what specific condition does the Steady-State Approximation (SSA) yield a rate law identical to the Pre-equilibrium Approximation?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_085",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "The Rate-Determining Step Trap",
    "question": "Is the rate of a reaction always equal to the rate of the slowest step?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) While the slowest step limits the rate",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_086",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Negative Absolute Temp",
    "question": "(EXPERT TRAP) In statistical mechanics",
    "options": [],
    "correctOption": "a system with negative absolute temperature (e.g.",
    "analysis": "certain nuclear spins) is physically:",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_087",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "The Nernst Equation at Equilibrium",
    "question": "What is the value of the cell potential (<i>E</i>) when a redox system reaches equilibrium?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) At equilibrium",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_088",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Norrish Type II Trap",
    "question": "(EXPERT TRAP) In the Norrish Type II photolysis of 2-pentanone",
    "options": [],
    "correctOption": "why is the reaction suppressed if the gamma-hydrogen is replaced by a methyl group?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_089",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Nucleophilic Substitution on Neopentyl",
    "question": "Why is neopentyl bromide extremely slow in S<sub>N</sub>2 reactions despite being a primary halide?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) Although the alpha-carbon is primary",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_090",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "The Ilkovič Equation",
    "question": "(EXPERT TRAP) In polarography",
    "options": [],
    "correctOption": "the limiting diffusion current (<i>i</i><sub>d</sub>) is proportional to the concentration of the analyte. What is the dependence of <i>i</i><sub>d</sub> on the mercury drop mass flow rate (<i>m</i>)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_091",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Entropy of Mixing Real Gases",
    "question": "For two real gases",
    "options": [],
    "correctOption": "is the entropy of mixing (Δ<i>S</i><sub>mix</sub>) always positive?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_092",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Quantum Tunneling",
    "question": "(EXPERT TRAP) In the reaction of methyl radicals with hydrogen gas",
    "options": [],
    "correctOption": "the observed rate at very low temperatures is significantly higher than predicted by the Arrhenius equation. This is primarily due to:",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_093",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Activation Energy and Exothermicity",
    "question": "Can a reaction be highly exothermic and yet extremely slow at room temperature?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) Exothermicity relates to the total energy released (thermodynamics)",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_094",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Residual Entropy",
    "question": "(EXPERT TRAP) Why does crystalline carbon monoxide (CO) have a molar entropy of approximately 4.6 J K<sup>−1</sup> mol<sup>−1</sup> at <i>T</i> = 0 K?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) The CO molecule is nearly symmetric. As it freezes",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_095",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Standard Potentials and pH",
    "question": "Does the standard reduction potential (<i>E</i>°) of the <i>MnO</i><sub>4</sub><sup>−</sup>/<i>Mn</i><sup>2+</sup> couple depend on pH?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) <i>E</i>° is a constant defined at [<i>H</i><sup>+</sup>] = 1 M (pH 0). While the actual potential <i>E</i> changes with pH",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_096",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "Möbius-Hückel Topology",
    "question": "(EXPERT TRAP) According to the Möbius-Hückel concept",
    "options": [],
    "correctOption": "a cyclic conjugated system with 4n π-electrons is aromatic if it has:",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_097",
    "loreLabId": "organic-synthesis-matrix",
    "domain": "ORGANIC",
    "topic": "The Anti-Markovnikov Trap",
    "question": "Does the presence of peroxides change the mechanism of <i>HCl</i> addition to alkenes?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> (TRAP) The <i>H-Cl</i> bond is too strong for the second propagation step to be exothermic; thus",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_098",
    "loreLabId": "electro-voltaic-core",
    "domain": "ELECTRO",
    "topic": "Stern Double Layer Model",
    "question": "(EXPERT TRAP) In the Stern model of the electrical double layer",
    "options": [],
    "correctOption": "why does the capacitance of the interface not increase indefinitely with electrolyte concentration?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_099",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Vapor Pressure and Total Pressure",
    "question": "If you increase the total pressure on a liquid by adding an inert gas",
    "options": [],
    "correctOption": "does its vapor pressure change?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_100",
    "loreLabId": "catalyst-protocol",
    "domain": "KINETICS",
    "topic": "Marcus Inverted Region",
    "question": "(EXPERT TRAP) In Marcus Theory for electron transfer",
    "options": [],
    "correctOption": "what happens to the rate of reaction as the driving force (−Δ<i>G</i>°) becomes extremely large (greater than the reorganization energy λ)?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_101",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Thermodynamic Work Definitions",
    "question": "In a reversible isothermal expansion of an ideal gas",
    "options": [],
    "correctOption": "what is the formula for the work done by the system?",
    "analysis": "UP",
    "hint": "",
    "context": ""
  },
  {
    "id": "MSTR_102",
    "loreLabId": "thermo-dynamics-engine",
    "domain": "PHYSICAL",
    "topic": "Chemical Potential Basics",
    "question": "Which quantity equalizes at equilibrium between two phases of a pure substance?",
    "options": [],
    "correctOption": "UP",
    "analysis": "<b>Physical Principle:</b> At equilibrium between phases",
    "hint": "",
    "context": ""
  }
];
